-- Miaoda seed: roles, menus, role_menus, default admin
-- Prerequisite: drizzle migrations 0000-0012
-- Idempotent: safe to re-run

INSERT INTO roles (name, code, description, is_system) VALUES ('超级管理员', 'super_admin', '管理角色/菜单/用户', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO roles (name, code, description, is_system) VALUES ('PMC 计划员', 'pmc_planner', '管理 PMC 计划', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO roles (name, code, description, is_system) VALUES ('仓库员', 'warehouse', '录入库存/出入库', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO roles (name, code, description, is_system) VALUES ('采购员', 'purchaser', '管理采购/补货', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO roles (name, code, description, is_system) VALUES ('只读查看', 'viewer', '只读访问', true) ON CONFLICT (code) DO NOTHING;

INSERT INTO menus (name, code, icon, path, parent_id, sort_order, is_leaf) SELECT '经营看板', 'dashboard', 'LayoutDashboard', '/dashboard', NULL, 0, true WHERE NOT EXISTS (SELECT 1 FROM menus WHERE code = 'dashboard');
INSERT INTO menus (name, code, icon, path, parent_id, sort_order, is_leaf) SELECT '库存管理', 'inventory', 'Package', NULL, NULL, 1, false WHERE NOT EXISTS (SELECT 1 FROM menus WHERE code = 'inventory');
INSERT INTO menus (name, code, icon, path, parent_id, sort_order, is_leaf) SELECT '库存总览', 'inventory.overview', NULL, '/inventory/overview', (SELECT id FROM menus WHERE code = 'inventory' LIMIT 1), 1, true WHERE NOT EXISTS (SELECT 1 FROM menus WHERE code = 'inventory.overview');
INSERT INTO menus (name, code, icon, path, parent_id, sort_order, is_leaf) SELECT '安全库存设置', 'inventory.safety', NULL, '/inventory/safety', (SELECT id FROM menus WHERE code = 'inventory' LIMIT 1), 2, true WHERE NOT EXISTS (SELECT 1 FROM menus WHERE code = 'inventory.safety');
INSERT INTO menus (name, code, icon, path, parent_id, sort_order, is_leaf) SELECT '缺货预警', 'inventory.alert', NULL, '/inventory/alerts', (SELECT id FROM menus WHERE code = 'inventory' LIMIT 1), 3, true WHERE NOT EXISTS (SELECT 1 FROM menus WHERE code = 'inventory.alert');
INSERT INTO menus (name, code, icon, path, parent_id, sort_order, is_leaf) SELECT '下单计划', 'pmc', 'ClipboardList', NULL, NULL, 2, false WHERE NOT EXISTS (SELECT 1 FROM menus WHERE code = 'pmc');
INSERT INTO menus (name, code, icon, path, parent_id, sort_order, is_leaf) SELECT '补货建议', 'pmc.suggestion', NULL, '/pmc/suggestions', (SELECT id FROM menus WHERE code = 'pmc' LIMIT 1), 1, true WHERE NOT EXISTS (SELECT 1 FROM menus WHERE code = 'pmc.suggestion');
INSERT INTO menus (name, code, icon, path, parent_id, sort_order, is_leaf) SELECT '计划列表', 'pmc.list', NULL, '/pmc/list', (SELECT id FROM menus WHERE code = 'pmc' LIMIT 1), 2, true WHERE NOT EXISTS (SELECT 1 FROM menus WHERE code = 'pmc.list');
INSERT INTO menus (name, code, icon, path, parent_id, sort_order, is_leaf) SELECT '采购跟单', 'pmc.tracking', NULL, '/pmc/tracking', (SELECT id FROM menus WHERE code = 'pmc' LIMIT 1), 3, true WHERE NOT EXISTS (SELECT 1 FROM menus WHERE code = 'pmc.tracking');
INSERT INTO menus (name, code, icon, path, parent_id, sort_order, is_leaf) SELECT '合规管理', 'compliance', 'Shield', NULL, NULL, 3, false WHERE NOT EXISTS (SELECT 1 FROM menus WHERE code = 'compliance');
INSERT INTO menus (name, code, icon, path, parent_id, sort_order, is_leaf) SELECT '合规总览', 'compliance.overview', NULL, '/compliance/overview', (SELECT id FROM menus WHERE code = 'compliance' LIMIT 1), 1, true WHERE NOT EXISTS (SELECT 1 FROM menus WHERE code = 'compliance.overview');
INSERT INTO menus (name, code, icon, path, parent_id, sort_order, is_leaf) SELECT 'SKU 合规', 'compliance.skus', NULL, '/compliance/skus', (SELECT id FROM menus WHERE code = 'compliance' LIMIT 1), 2, true WHERE NOT EXISTS (SELECT 1 FROM menus WHERE code = 'compliance.skus');
INSERT INTO menus (name, code, icon, path, parent_id, sort_order, is_leaf) SELECT '物流管理', 'logistics', 'Truck', NULL, NULL, 4, false WHERE NOT EXISTS (SELECT 1 FROM menus WHERE code = 'logistics');
INSERT INTO menus (name, code, icon, path, parent_id, sort_order, is_leaf) SELECT 'FOB分账', 'logistics.fob_settlement', NULL, '/logistics/fob-settlement', (SELECT id FROM menus WHERE code = 'logistics' LIMIT 1), 1, true WHERE NOT EXISTS (SELECT 1 FROM menus WHERE code = 'logistics.fob_settlement');
INSERT INTO menus (name, code, icon, path, parent_id, sort_order, is_leaf) SELECT 'AI 知识库', 'ai', 'Bot', NULL, NULL, 5, false WHERE NOT EXISTS (SELECT 1 FROM menus WHERE code = 'ai');
INSERT INTO menus (name, code, icon, path, parent_id, sort_order, is_leaf) SELECT '知识问答', 'ai.chat', NULL, '/ai/chat', (SELECT id FROM menus WHERE code = 'ai' LIMIT 1), 1, true WHERE NOT EXISTS (SELECT 1 FROM menus WHERE code = 'ai.chat');
INSERT INTO menus (name, code, icon, path, parent_id, sort_order, is_leaf) SELECT '数据中心', 'data', 'ClipboardList', NULL, NULL, 6, false WHERE NOT EXISTS (SELECT 1 FROM menus WHERE code = 'data');
INSERT INTO menus (name, code, icon, path, parent_id, sort_order, is_leaf) SELECT '商品主数据', 'data.products', NULL, '/data/products', (SELECT id FROM menus WHERE code = 'data' LIMIT 1), 1, true WHERE NOT EXISTS (SELECT 1 FROM menus WHERE code = 'data.products');
INSERT INTO menus (name, code, icon, path, parent_id, sort_order, is_leaf) SELECT '数据导入', 'data.import', NULL, '/data/import', (SELECT id FROM menus WHERE code = 'data' LIMIT 1), 2, true WHERE NOT EXISTS (SELECT 1 FROM menus WHERE code = 'data.import');
INSERT INTO menus (name, code, icon, path, parent_id, sort_order, is_leaf) SELECT '销量历史', 'data.sales', NULL, '/data/sales', (SELECT id FROM menus WHERE code = 'data' LIMIT 1), 3, true WHERE NOT EXISTS (SELECT 1 FROM menus WHERE code = 'data.sales');
INSERT INTO menus (name, code, icon, path, parent_id, sort_order, is_leaf) SELECT '帮助中心', 'help', 'HelpCircle', '/help', NULL, 98, true WHERE NOT EXISTS (SELECT 1 FROM menus WHERE code = 'help');
INSERT INTO menus (name, code, icon, path, parent_id, sort_order, is_leaf) SELECT '系统设置', 'system', 'Settings', NULL, NULL, 99, false WHERE NOT EXISTS (SELECT 1 FROM menus WHERE code = 'system');
INSERT INTO menus (name, code, icon, path, parent_id, sort_order, is_leaf) SELECT '用户管理', 'system.users', NULL, '/system/users', (SELECT id FROM menus WHERE code = 'system' LIMIT 1), 1, true WHERE NOT EXISTS (SELECT 1 FROM menus WHERE code = 'system.users');
INSERT INTO menus (name, code, icon, path, parent_id, sort_order, is_leaf) SELECT '角色与菜单', 'system.roles', NULL, '/system/roles', (SELECT id FROM menus WHERE code = 'system' LIMIT 1), 2, true WHERE NOT EXISTS (SELECT 1 FROM menus WHERE code = 'system.roles');

INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'super_admin' AND m.code = 'dashboard' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'super_admin' AND m.code = 'inventory' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'super_admin' AND m.code = 'inventory.overview' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'super_admin' AND m.code = 'inventory.safety' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'super_admin' AND m.code = 'inventory.alert' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'super_admin' AND m.code = 'pmc' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'super_admin' AND m.code = 'pmc.suggestion' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'super_admin' AND m.code = 'pmc.list' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'super_admin' AND m.code = 'pmc.tracking' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'super_admin' AND m.code = 'compliance' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'super_admin' AND m.code = 'compliance.overview' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'super_admin' AND m.code = 'compliance.skus' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'super_admin' AND m.code = 'logistics' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'super_admin' AND m.code = 'logistics.fob_settlement' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'super_admin' AND m.code = 'data' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'super_admin' AND m.code = 'data.products' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'super_admin' AND m.code = 'data.import' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'super_admin' AND m.code = 'data.sales' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'super_admin' AND m.code = 'ai' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'super_admin' AND m.code = 'ai.chat' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'super_admin' AND m.code = 'help' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'super_admin' AND m.code = 'system' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'super_admin' AND m.code = 'system.users' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'super_admin' AND m.code = 'system.roles' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'pmc_planner' AND m.code = 'dashboard' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'pmc_planner' AND m.code = 'inventory' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'pmc_planner' AND m.code = 'inventory.overview' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'pmc_planner' AND m.code = 'inventory.safety' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'pmc_planner' AND m.code = 'pmc' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'pmc_planner' AND m.code = 'pmc.suggestion' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'pmc_planner' AND m.code = 'pmc.list' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'pmc_planner' AND m.code = 'compliance' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'pmc_planner' AND m.code = 'compliance.overview' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'pmc_planner' AND m.code = 'compliance.skus' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'pmc_planner' AND m.code = 'logistics' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'pmc_planner' AND m.code = 'logistics.fob_settlement' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'pmc_planner' AND m.code = 'data' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'pmc_planner' AND m.code = 'data.products' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'pmc_planner' AND m.code = 'data.import' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'pmc_planner' AND m.code = 'data.sales' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'pmc_planner' AND m.code = 'ai' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'pmc_planner' AND m.code = 'ai.chat' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'pmc_planner' AND m.code = 'help' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'warehouse' AND m.code = 'dashboard' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'warehouse' AND m.code = 'inventory' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'warehouse' AND m.code = 'inventory.overview' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'warehouse' AND m.code = 'inventory.alert' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'warehouse' AND m.code = 'pmc' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'warehouse' AND m.code = 'pmc.list' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'warehouse' AND m.code = 'compliance' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'warehouse' AND m.code = 'compliance.overview' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'warehouse' AND m.code = 'compliance.skus' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'warehouse' AND m.code = 'logistics' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'warehouse' AND m.code = 'logistics.fob_settlement' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'warehouse' AND m.code = 'data' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'warehouse' AND m.code = 'data.products' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'warehouse' AND m.code = 'data.import' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'warehouse' AND m.code = 'data.sales' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'warehouse' AND m.code = 'ai' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'warehouse' AND m.code = 'ai.chat' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'warehouse' AND m.code = 'help' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'purchaser' AND m.code = 'dashboard' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'purchaser' AND m.code = 'inventory' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'purchaser' AND m.code = 'inventory.overview' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'purchaser' AND m.code = 'inventory.safety' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'purchaser' AND m.code = 'inventory.alert' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'purchaser' AND m.code = 'pmc' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'purchaser' AND m.code = 'pmc.list' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'purchaser' AND m.code = 'pmc.tracking' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'purchaser' AND m.code = 'compliance' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'purchaser' AND m.code = 'compliance.overview' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'purchaser' AND m.code = 'compliance.skus' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'purchaser' AND m.code = 'logistics' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'purchaser' AND m.code = 'logistics.fob_settlement' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'purchaser' AND m.code = 'data' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'purchaser' AND m.code = 'data.products' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'purchaser' AND m.code = 'data.import' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'purchaser' AND m.code = 'data.sales' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'purchaser' AND m.code = 'ai' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'purchaser' AND m.code = 'ai.chat' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'purchaser' AND m.code = 'help' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'viewer' AND m.code = 'dashboard' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'viewer' AND m.code = 'inventory' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'viewer' AND m.code = 'inventory.overview' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'viewer' AND m.code = 'pmc' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'viewer' AND m.code = 'pmc.suggestion' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'viewer' AND m.code = 'pmc.list' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'viewer' AND m.code = 'pmc.tracking' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'viewer' AND m.code = 'compliance' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'viewer' AND m.code = 'compliance.overview' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'viewer' AND m.code = 'compliance.skus' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'viewer' AND m.code = 'logistics' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'viewer' AND m.code = 'logistics.fob_settlement' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'viewer' AND m.code = 'data' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'viewer' AND m.code = 'data.sales' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'viewer' AND m.code = 'ai' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'viewer' AND m.code = 'ai.chat' ON CONFLICT (role_id, menu_id) DO NOTHING;
INSERT INTO role_menus (role_id, menu_id) SELECT r.id, m.id FROM roles r, menus m WHERE r.code = 'viewer' AND m.code = 'help' ON CONFLICT (role_id, menu_id) DO NOTHING;

INSERT INTO users (name, email, role_id, is_active) SELECT '系统管理员', 'admin@scm.local', r.id, true FROM roles r WHERE r.code = 'super_admin' AND NOT EXISTS (SELECT 1 FROM users WHERE email = 'admin@scm.local');

